### ISSUE TITLE
deleteDirectory -p /policyman

### ISSUE THREAD

**Issue by ibnbax** [JohnBel/EfsTools#1]
the best tool ever
but please add EfsTools.exe deleteDirectory -p /policyman
 because it cannot be deleted 

EfsTools.exe deleteDirectory -p /policyman

Error on delete directory '/policyman'. EFS error. Code = 39
pls fix

**Comment by JohnBel** [comment]
Fixed in EfsTools 0.4 http://johnbel.github.io/2018/11/05/efstools-0-4-release.html

**Comment by ibnbax** [comment]
Thank you so much my friend
Большое спасибо моему другу
Best regards
