### ISSUE TITLE
EfsTools_0.12 Critical error. Bad command

### ISSUE THREAD

**Issue by rina2016** [JohnBel/EfsTools#2]
When I run EfsTools.exe efsInfo, I get the following error:
Critical error. Bad command
EfsTools_0.11 works fine.

Windows 10 ver 2004 build 19041.329
Xperia 1 II XQ-AT52

**Comment by amrashraf1992** [comment]
i have same issue also

**Comment by amrashraf1992** [comment]
I think this issue related to modem X55

**Comment by JohnBel** [comment]
Fixed in commit e9482c8
