### ISSUE TITLE
Critical error. Bad command

### ISSUE THREAD

**Issue by amrashraf1992** [JohnBel/EfsTools#3]
D:\LyticsHub\OnePlus 6T\EfsTools-0.13\EfsTools-0.13>EfsTools.exe writeFile -i mcfg_autoselect_by_uim -o /nv/item_files/mcfg/mcfg_autoselect_by_uim
Use serial port 'COM21'
Critical error. Bad command

Mobile Samsung S20 Ultra 5G (Modem X55)

**Comment by JohnBel** [comment]
Fixed in commit e9482c8
